# Generated by Django 4.1.6 on 2023-02-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_id_myuser_idd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='idd',
            new_name='id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
